# Please refer to the official golangci-lint config documentation for more details:
# https://golangci-lint.run/usage/configuration/
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

linters:
  enable-all: true

run:
  timeout: 10m
  tests: false

issues:
  max-issues-per-linter: 1000
  exclude-rules:
  - path: vm/contracts.go
    text: 'SA1019: "golang.org/x/crypto/ripemd160" is deprecated: RIPEMD-160 is a legacy hash and should not be used for new applications.'
  - path: vm/bn256/cloudflare/optate.go
    linters:
      - deadcode
      - staticcheck
