# goreleaser is currently used to attach binaries to github releases
# it can be exteneded in the future to also publish docker images, brew, chocolatey, etc.
version: 2

before:
  hooks:
    - go mod tidy
    - go mod vendor

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    id: thor
    hooks:
      pre: make thor
    binary: ./bin/thor
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    id: disco
    binary: ./bin/disco
    hooks:
      pre: make disco

release:
  github:
    owner: darrenvecahin
    name: thor

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md
