# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
pro: true
project_name: thor

metadata:
  license: "LGPL-3.0"
  homepage: "https://github.com/{{ .Env.REPOSITORY }}"
  description: "A general purpose blockchain highly compatible with Ethereum's ecosystem"
  full_description: "Thor is the official Golang client for VeChainThor, the public blockchain powering the VeChain ecosystem. VeChainThor is designed for real-world adoption, enabling scalable, low-cost, and sustainable applications."

partial:
  by: target

builds:
  - id: "thor"
    main: ./cmd/thor
    binary: thor
    ldflags:
      - -s -w
      - -X main.version={{.Env.THOR_VERSION}}
      - -X main.gitCommit={{.ShortCommit}}
      - -X main.gitTag={{.Tag}}
      - -X main.copyrightYear={{.Env.COPYRIGHT_YEAR}}
    env:
      - CGO_ENABLED=1
  - id: "disco"
    main: ./cmd/disco
    binary: disco
    ldflags:
      - -s -w
      - -X main.version={{.Env.DISCO_VERSION}}
      - -X main.gitCommit={{.ShortCommit}}
      - -X main.gitTag={{.Tag}}
      - -X main.copyrightYear={{.Env.COPYRIGHT_YEAR}}
    env:
      - CGO_ENABLED=1

archives:
  - formats: [ 'tar.gz' ]
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: '{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

snapshot:
  version_template: SNAPSHOT-{{ .Commit }}

checksum:
  disable: false
  name_template: '{{ .ProjectName }}-{{ .Tag }}-checksums.txt'

release:
  skip_upload: false
  github:
    owner: vecahin
    name: thor
  header: |
    Thor is the official Golang client for VeChainThor, the public blockchain powering the VeChain ecosystem. VeChainThor is designed for real-world adoption, enabling scalable, low-cost, and sustainable applications.

changelog:
  disable: true

source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Tag }}-source'

homebrew_casks:
  # https://goreleaser.com/customization/homebrew_casks/
  - name: vechain-thor
    alternative_names:
      - vechain-thor@{{ .Tag }}
    ids:
      - thor
      - disco
    binary: thor
    skip_upload: '{{ if .IsRelease }}false{{ else }}true{{ end }}'
    description: A general purpose blockchain highly compatible with Ethereum's ecosystem
    homepage: 'https://github.com/{{ .Env.REPOSITORY }}'
    license: LGPL-3.0
    url:
      template: "https://github.com/{{ .Env.REPOSITORY }}/releases/download/{{ .Tag }}/thor-{{ .Tag }}-darwin-{{ .Arch }}.tar.gz"
    repository:
      git:
        url: 'git@github.com:{{ .Env.REPOSITORY }}.git'

npms:
  - name: "@{{ .Env.REPOSITORY }}"
    repository: 'https://github.com/{{ .Env.REPOSITORY }}'
    bugs: 'https://github.com/{{ .Env.REPOSITORY }}/issues'
    description: A general purpose blockchain highly compatible with Ethereum's ecosystem
    homepage: 'https://github.com/{{ .Env.REPOSITORY }}'
    license: LGPL-3.0
    access: public
    keywords:
      - vechain
      - thor
    files:
      - README.md

nfpms:
  - id: vechain-thor
    package_name: '{{ .Env.REPOSITORY }}'
    description: A general purpose blockchain highly compatible with Ethereum's ecosystem
    homepage: 'https://github.com/{{ .Env.REPOSITORY }}'
    if: '{{ eq .Os "linux" }}'
    file_name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    license: GPLv3
    ids:
      - disco
      - thor
    maintainer: protocol@vechain.org
    vendor: vechain
    formats:
      - deb
      - rpm
      - apk
    umask: 0o022
    contents:
      - src: LICENSE
        dst: /usr/share/doc/thor/copyright
      - src: README.md
        dst: /usr/share/doc/thor/README.md
    rpm:
      group: Unspecified

dockers:
  - id: "thor"
    goarch: '{{ .Runtime.Goarch }}'
    goos: linux
    image_templates:
      - '{{ if .IsRelease }}ghcr.io/{{ .Env.REPOSITORY }}:{{ .Tag }}-{{ .Runtime.Goarch }}{{ end }}'
      - '{{ if .IsSnapshot }}ghcr.io/{{ .Env.REPOSITORY }}:{{ .ShortCommit }}-{{ .CommitTimestamp }}{{ .Runtime.Goarch }}{{ end }}'
    ids:
      - thor
      - disco
    dockerfile: goreleaser.Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description=A general purpose blockchain highly compatible with Ethereum's ecosystem"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.url={{.GitURL}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Tag}}"
      - "--label=org.opencontainers.image.licenses=LGPL-3.0"

docker_manifests:
  - name_template: '{{ .Env.REPOSITORY }}:latest'
    image_templates:
      - 'ghcr.io/{{ .Env.REPOSITORY }}:{{ .Tag }}-amd64'
      - 'ghcr.io/{{ .Env.REPOSITORY }}:{{ .Tag }}-arm64'
    skip_push: '{{ if not .IsRelease }}true{{ else }}false{{ end }}'

  - name_template: 'ghcr.io/{{ .Env.REPOSITORY }}:latest'
    image_templates:
      - 'ghcr.io/{{ .Env.REPOSITORY }}:{{ .Tag }}-amd64'
      - 'ghcr.io/{{ .Env.REPOSITORY }}:{{ .Tag }}-arm64'
    skip_push: '{{ if not .IsRelease }}true{{ else }}false{{ end }}'

  - name_template: '{{ .Env.REPOSITORY }}:{{ .Tag }}'
    image_templates:
      - 'ghcr.io/{{ .Env.REPOSITORY }}:{{ .Tag }}-amd64'
      - 'ghcr.io/{{ .Env.REPOSITORY }}:{{ .Tag }}-arm64'
    skip_push: '{{ if not .IsRelease }}true{{ else }}false{{ end }}'

  - name_template: 'ghcr.io/{{ .Env.REPOSITORY }}:{{ .Tag }}'
    image_templates:
      - 'ghcr.io/{{ .Env.REPOSITORY }}:{{ .Tag }}-amd64'
      - 'ghcr.io/{{ .Env.REPOSITORY }}:{{ .Tag }}-arm64'
    skip_push: '{{ if not .IsRelease }}true{{ else }}false{{ end }}'

  - name_template: 'ghcr.io/{{ .Env.REPOSITORY }}:{{ .ShortCommit }}-{{ .CommitTimestamp }}'
    image_templates:
      - 'ghcr.io/{{ .Env.REPOSITORY }}:{{ .ShortCommit }}-{{ .CommitTimestamp }}-amd64'
      - 'ghcr.io/{{ .Env.REPOSITORY }}:{{ .ShortCommit }}-{{ .CommitTimestamp }}-arm64'
    skip_push: '{{ if .IsSnapshot }}false{{ else }}true{{ end }}'

docker_digest:
  name_template: "{{ProjectName}}_digest.txt"
