version: "3.8"

services:
  base-authority-node:
    build:
      context: ..
      dockerfile: Dockerfile
    entrypoint: "/node/config/start.sh"
    networks:
      - thor
    volumes:
      - type: bind
        source: ./config
        target: /node/config
      - type: bind
        source: ./keys
        target: /node/keys

networks:
  thor:
    external: true
