name: E2E Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: vechain/thor:${{ github.sha }}
          outputs: type=docker,dest=/tmp/vechain-thor.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: vechain-thor-image
          path: /tmp/vechain-thor.tar
          retention-days: 7

  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: vechain-thor-image
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/vechain-thor.tar
          docker image ls -a   
