name: Integration Tests

on: [push, pull_request]

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Compose
        run: |
          docker-compose -f integration_tests/network/docker-compose.yaml up -d --wait 

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run Tests
        run: |
          cd integration_tests
          yarn install
          yarn test
