name: On Master Commit

on:
  push:
    branches:
      - master

jobs:

  unit-tests:
    uses: ./.github/workflows/unit-tests.yaml
    secrets: inherit

  code-coverage-scan:
    uses: ./.github/workflows/code-coverage-scan.yaml
    secrets: inherit

  test-docker-build:
    uses: ./.github/workflows/test-docker-build.yaml
    secrets: inherit
