name: Pre-Release CI

on:
  release:
    types:
      - prereleased

jobs:
  run-unit-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/test.yaml

  verify-tag:
    name: Verify Tag
    runs-on: ubuntu-latest
    steps:
      - name: Verify Tag
        if: "!endsWith(github.event.release.tag_name, '-rc.*')"
        run: |
          echo "Invalid RC tag. Please use the format vX.Y.Z-rc.N"
          exit 1

  publish-docker-image:
    name: Publish Pre-Release Docker Image
    uses: ./.github/workflows/publish-docker-images.yaml
    secrets: inherit
    needs:
      - run-unit-tests
      - verify-tag
    permissions:
      contents: read
      packages: write
    with:
      environment: docker-publish
      images: |
        ${{ github.repository }}
        ghcr.io/${{ github.repository }}
      tags: |
        type=raw,value=${{ github.event.release.tag_name }}
