name: Pre-Release CI

on:
  push:
    tags:
      - 'v*.*.*-rc.*'

jobs:
  run-unit-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/test.yaml

  publish-docker-image:
    name: Publish Pre-Release Docker Image
    uses: ./.github/workflows/publish-docker-images.yaml
    secrets: inherit
    if: endsWith(github.event.release.tag_name, '-rc.*')
    needs:
      - run-unit-tests
    permissions:
      contents: read
      packages: write
    with:
      environment: docker-publish
      images: |
        ${{ github.repository }}
        ghcr.io/${{ github.repository }}
      tags: |
        type=raw,value=${{ github.ref_name }}
