name: Pull Request

on:
  pull_request:
    branches:
      - master

# Cancel the previous workflow run if a new one is triggered
concurrency:
  group: ${{ github.head_ref || github.ref_name }}-pr
  cancel-in-progress: true

jobs:

  debug-qodana-secret:
    permissions:
      contents: read
    environment: pull-requests
    runs-on: ubuntu-latest
    steps:
      - name: Debug Token
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        run: |
          TOKEN_LENGTH=$(echo -n $QODANA_TOKEN | wc -c)
          echo "Length of Qodana Token: $TOKEN_LENGTH"

#  unit-tests:
#    uses: ./.github/workflows/unit-tests.yaml
#    secrets: inherit
#
#  code-coverage-scan:
#    uses: ./.github/workflows/test-coverage-scan.yaml
#    secrets: inherit
#
#  test-docker-build:
#    uses: ./.github/workflows/test-docker-build.yaml
#    secrets: inherit
