name: Release CI

on:
  push:
    tags:
      - 'v*.*.*'
      - '!v*.*.*-rc*'

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Publish Binaries
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean --timeout=90m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-docker-image:
    name: Publish Docker Image
    uses: ./.github/workflows/publish-docker-images.yaml
    secrets: inherit
    needs:
      - validate
    permissions:
      contents: read
      packages: write
    with:
      environment: docker-publish
      images: |
        ${{ github.repository }}
        ghcr.io/${{ github.repository }}
      tags: |
        type=raw,value=${{ github.ref_name }}
        type=raw,value=latest
