name: goreleaser

on:
  pull_request:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ${{ matrix.hostos }}
    strategy:
      matrix:
        include:
        - goos: linux
          goarch: amd64
          hostos: ubuntu-latest
        - goos: linux
          goarch: arm64
          hostos: ubuntu-24.04-arm
        - goos: darwin
          goarch: arm64
          hostos: macos-latest
        - goos: windows
          goarch: amd64
          hostos: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true

      - name: Build
        run: goreleaser build --single-target
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
