name: Code Coverage + Scan

on:
  workflow_call:

jobs:
  test_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Make all
        run: make all

      - name: Make Coverage
        run: make test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Setup Qodana
        run: |
          mkdir -p .qodana/code-coverage
          cp coverage.out .qodana/code-coverage/coverage.out

      - name: Debug Token
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        run: |
          TOKEN_LENGTH=$(echo -n $QODANA_TOKEN | wc -c)
          echo "Length of Qodana Token: $TOKEN_LENGTH"

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          pr-mode: ${{ github.event_name == 'pull_request' }}
          fetch-depth: 0
