name: E2E Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-docker-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: vechain/thor:${{ github.sha }}
          outputs: type=docker,dest=/tmp/vechain-thor.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: vechain-thor-image
          path: /tmp/vechain-thor.tar
          retention-days: 7

  run-tests:
    runs-on: ubuntu-latest
    needs: build-docker-image
    env:
      THOR_IMAGE: vechain/thor:${{ github.sha }}
    name: Run E2E Tests
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: vechain-thor-image
          path: /tmp

      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Load image
        run: |
          docker load --input /tmp/vechain-thor.tar
          docker image ls -a

      - name: Run Tests
        working-directory: ./tests/thor-e2e-tests
        run: |
          export THOR_IMAGE=vechain/thor:${{ github.sha }}
          yarn install
          yarn test

      - name: Publish Results
        uses: dorny/test-reporter@v1
        id: test-reporter
        if: success() || failure()
        with:
          name: Integration Tests
          only-summary: 'false'
          list-suites: 'all'
          list-tests: 'all'
          fail-on-error: 'true'
          reporter: "jest-junit"
          path: |
            ./tests/thor-e2e-tests/junit.xml

      - name: Echo Report URL
        run: |
          echo ${{steps.test-reporter.outputs.url_html}}
